### ISSUE TITLE
Possible plagiary of my repository

### ISSUE THREAD

**Issue by Ornolfr** [borjabravo10/SimpleRatingBar#1]
Hope you're doing fine. But it seems that you just rewrote my repository https://github.com/Ornolfr/RatingView in Kotlin.

**Comment by borjabravo10** [comment]
Hi @Ornolfr,
It is true that I have taken your project as base, trying to improve some behaviors that seemed to me to be better. For example, add parameter changes dynamically and refresh the view automatically.
I link you in the Readme to indicate that it is based on your project. Do you think it's OK?
If I did not do a fork it was because I intended to do it in Kotlin to write less code.

Anything you tell me. Regards,

**Comment by borjabravo10** [comment]
@Ornolfr Commented on Readme to your project: https://github.com/borjabravo10/SimpleRatingBar/commit/b8b8a6098006253c225efc979206c479de1a29ae
